In [ ]:
# Python DA Assignment 1:  Data Analysis using NumPy and Pandas

In [ ]:
## Numpy Array Operations:

In [ ]:
### 1. Create a 1D NumPy Array:

import numpy as np

temperatures_w1 = np.array([22.5,25.3,20.8,23.4,26.1,24.8,21.9])
temperatures_w1

array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

In [ ]:
### 2. Inspection and Properties:
'''Inspect the shape, data type, and the number of elements in the array.
Inspect the shape of the temperatures_w1 array.'''

print("shape of array:",temperatures_w1.shape)
print("type of array:",temperatures_w1.dtype)
print("size of array:",temperatures_w1.size)

shape of array: (7,)
type of array: float64
size of array: 7


In [ ]:
### 3. Array Operations:
'''Convert the temperatures_w1 from Celsius to Fahrenheit using the
formula: Fahrenheit = (Celsius * 9/5) + 32.'''

fahrenheit_w1 = (temperatures_w1 * 9/5) + 32
print(fahrenheit_w1)

'''Find the maximum, minimum, and mean temperatures for the week. '''

print("maximum temperature for week:", max(temperatures_w1))
print("minimum temperature for week:", min(temperatures_w1))
print("mean temperature for week:",round(temperatures_w1.mean(),3))



[72.5  77.54 69.44 74.12 78.98 76.64 71.42]
maximum temperature for week: 26.1
minimum temperature for week: 20.8
mean temperature for week: 23.543


In [ ]:
### 4. Array Slicing and Indexing:
'''Extract the temperatures for the first three days of the week. '''
print("temperatures for the first three days of week:",temperatures_w1[:3])

'''Extract the temperatures for the weekend (last two days). '''
print("temperatures for the weekend(last two days):", temperatures_w1[-2:])

'''Extract the temperatures for the middle three days of the week. '''
print("temperatures for the middle three days of the week:", temperatures_w1[2:5])

temperatures for the first three days of week: [22.5 25.3 20.8]
temperatures for the weekend(last two days): [24.8 21.9]
temperatures for the middle three days of the week: [20.8 23.4 26.1]


In [ ]:
### 5. Create a 2D Array:
temperatures = np.array([[22.5,25.3,20.8,23.4,26.1,24.8,21.9],[19.2,22.5,21.3,24.0,23.5,22.8,20.1]])
print(temperatures)

[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


In [ ]:
### 6. Inspect and Slice the 2D Array:
'''Inspect and print the shape, data type, and total number of elements in the
temperatures array. '''

print("shape of array:", temperatures.shape)
print("data type of array:", temperatures.dtype)
print("number of elements:", temperatures.size)

'''Extract the temperatures for each week and the weekends (last two days)
for both weeks.'''

print("week 1 temperature:",temperatures[0])
print("week 2 temperature:",temperatures[1])
print("weekends (last two days)both weeks:",temperatures[:,-2:] )


shape of array: (2, 7)
data type of array: float64
number of elements: 14
week 1 temperature: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
week 2 temperature: [19.2 22.5 21.3 24.  23.5 22.8 20.1]
weekends (last two days)both weeks: [[24.8 21.9]
 [22.8 20.1]]


In [ ]:
## Pandas Series:

In [ ]:
### 1. Creating Pandas Series:

import pandas as pd
marks = pd.Series([95,92,89,85,80],index=['Rank1','Rank2','Rank3','Rank4','Rank5'])
print(marks)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


In [ ]:
### 2. Indexing and Slicing:
'''Use the integer index position to access the mark of the 1st rank student. '''

print("1st rank student mark:", marks[0])

'''Use the loc accessor to retrieve the marks of the top 3 ranks by
specifying their index labels. '''

print("\nTop 3 Ranks:",'\n',marks.loc['Rank1':'Rank3'])

'''Use the iloc accessor to retrieve the mark of the 3rd rank student. '''

print("\nMark of third rank student:", marks.iloc[2])

'''Apply a boolean mask to filter the Series and retrieve the ranks where the
marks are greater than 90.'''

marks[marks>90]

1st rank student mark: 95

Top 3 Ranks: 
 Rank1    95
Rank2    92
Rank3    89
dtype: int64

Mark of third rank student: 89


/tmp/ipython-input-369849076.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print("1st rank student mark:", marks[0])


Rank1    95
Rank2    92
dtype: int64

In [ ]:
### 3. Manipulating Series:
'''Modify the mark of the student with the 1st rank to 100.  '''
marks.loc['Rank1']=100
print(marks)
'''Remove the entry corresponding to the last rank from the Series.'''
marks.drop('Rank5',inplace=True)
print('\n',marks)
'''Compute the CGPA by dividing each mark in the Series by 10.'''
CGPA=marks/10
print('\nCGPA:','\n', CGPA)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64

 Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64

CGPA: 
 Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


In [ ]:
## Pandas DataFrame:

In [ ]:
### 1. Creating Pandas DataFrame:

transactions=pd.DataFrame(
    {
    'TransactionID':[101,102,103,104,105,106,107,108,109,110],
    'ProductCategory':['Electronics', 'Clothing', 'Electronics', 'Furniture',
'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
    'Region':['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West',
'South', 'North'],
    'Amount':[200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
}
    )
print(transactions)


   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [ ]:
### 2. Data Exploration:
print(transactions)
print("\nInformation of dataframe:")
print(transactions.info())
print("\nHead of dataframe:")
print(transactions.head())
print("\nTail of dataframe:")
print(transactions.tail())
print("\nShape of dataframe:")
print(transactions.shape)
print("\nColumn names of dataframe:")
print(transactions.columns.tolist())
print("\nDatatype of dataframe:")
print(transactions.dtypes)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

Information of dataframe:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   TransactionID    10 non-null     int64 
 1   ProductCategory  10 non-null     object
 2   Region           10 non-null     object
 3   Amount           10 non-null     int64 
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes
None

Head of dataf

In [ ]:
'''Display only the 'ProductCategory' and 'Amount' columns.'''
transactions[['ProductCategory','Amount']]

ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400

In [ ]:
'''Retrieve the last 3 columns of the DataFrame using iloc or loc. '''
transactions.iloc[:,-3:]

ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400

In [ ]:
'''Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200.'''
transactions[(transactions['Region']=="North")&(transactions['Amount']>200)]

TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400

In [ ]:
'''Find the value counts for the 'ProductCategory' column.'''
transactions['ProductCategory'].value_counts()

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64

In [ ]:
'''Find the unique values in the 'Region' column. '''
transactions['Region'].unique()

array(['North', 'South', 'East', 'West'], dtype=object)

In [ ]:
'''Group by 'Region' and find the mean amount for each region.'''
transactions.groupby('Region')['Amount'].mean()


Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64

In [ ]:
### 3. Manipulating the DataFrame:

In [ ]:
'''Modify the 'Amount' for the transaction with TransactionID 102 to 165. '''
transactions.loc[transactions['TransactionID']==102, 'Amount']=165
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [ ]:
'''Add a new column 'Discount' by calculating 10% of the 'Amount'. '''
transactions['Discount']=transactions['Amount']*10/100
print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0


In [ ]:
'''Remove the row with TransactionID 109. '''
transactions.drop(transactions[transactions['TransactionID']==109].index)

TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0

In [ ]:
'''Delete the 'Discount' column from the DataFrame'''
del(transactions['Discount'])
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400
